create table public.players (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    name text not null default ''::text,
    defense smallint not null default '60'::smallint,
    offense smallint not null default '60'::smallint,
    passing smallint not null default '60'::smallint,
    shot smallint not null default '60'::smallint,
    skating smallint not null default '60'::smallint,
    stick smallint not null default '60'::smallint,
    attending boolean not null default false,
    constraint players_pkey primary key (id)
) tablespace pg_default;